### ISSUE TITLE
cannot run storybook

### ISSUE THREAD

**Issue by shootermv** [fabien0102/gatsby-starter#28]
reproduce:
run "yarn storybook"

lots of errors (wrote here only the first one)
ERROR in /Users/moshe/MyProjects/similarWebAssignment/node_modules/gatsby-link/index.d.ts
(8,78): error TS1005: '(' expected.

**Comment by beepiams** [comment]
+1

**Comment by fabien0102** [comment]
I got many problems since my last gatsby update (include storybook), I will try to get another try to update gatsby and fix all these problems 😉

Sorry for the lack of support, I was very busy this last month

**Comment by shootermv** [comment]
No probs bro. I wish i can help if it possible...

בתאריך 28 בספט׳ 2017 10:33 AM,‏ "Fabien BERNARD" <notifications@github.com>
כתב:

**Comment by fabien0102** [comment]
The last gatsby version works well with the starter (cf #30) 🎉 I'm working on storybook problem today, I've already update the storybook version, but many remaining incompatibilities issues…

**Comment by fabien0102** [comment]
Todo:

- [x] Update react
- [x] Update storybook
- [ ] Update template with `@storybook`
- [ ] Find and fix incompatibility bug

**Comment by fabien0102** [comment]
Closed with #30
