### ISSUE TITLE
Enable React production mode

### ISSUE THREAD

**Issue by ViliamKopecky** [fabien0102/gatsby-starter#39]
I can't find the reason this starter disables react production mode. I tried removing almost every plugin and configuration, but still. This doesnt happen on clean gatsby starter - even with `gatsby-plugin-typescript`.

```
VM2992:21 Uncaught Error: React is running in production mode, but dead code elimination has not been applied. Read how to correctly configure React for production: https://fb.me/react-perf-use-the-production-build     at <anonymous>:21:35
```

**Comment by fabien0102** [comment]
Interesting! No reason, it's a real bug :wink: I will try to check this tomorrow!

**Comment by resir014** [comment]
@fabien0102 Hey, this happens to me as well - I'm not using this starter kit, but it seems like it's a common issue among TypeScript at the moment.

My current hunch is that there's something that prevents `gatsby-plugin-typescript` to be perfectly chained with Babel, so many files come out unminified (see also: https://github.com/gatsbyjs/gatsby/issues/2771)

Here's an example of the output bundle that Gatsby generates.

![image](https://user-images.githubusercontent.com/5663877/32687110-a4b36870-c6e7-11e7-91cc-5ba10f6011b3.png)

**Comment by resir014** [comment]
My current workaround is to have this on `gatsby-node.js`:

```js
const extractQueryPlugin = path.resolve(
  __dirname,
  `node_modules/gatsby/dist/utils/babel-plugin-extract-graphql.js`
)

exports.modifyWebpackConfig = ({ config, stage }) => {
  if (stage === 'build-javascript') {
    // Temporary workaround.
    // Here we override the Webpack plugin during the `build-javascript` stage to make everything
    // compile down to es5 - turns out Webpack 1's UglifyJsPlugin doesn't like that we have some
    // ES6 stuff littered in our final bundle...
    config.loader('typescript', {
      test: /\.tsx?$/,
      loaders: [
        `babel-loader?${JSON.stringify({ presets: ['babel-preset-env'], plugins: [extractQueryPlugin] })}`,
        'ts-loader'
      ]
    })
  }
}
```
