### ISSUE TITLE
TypeError: Cannot read property 'children' of null

### ISSUE THREAD

**Issue by mghazwi** [fabien0102/gatsby-starter#46]
I downloaded the starter and the blog page has this error after I generated a blog post with 
npm run generate "blog post"
```
TypeError: Cannot read property 'children' of null
React.createElement.posts.map
src/pages/blog.tsx:34
  31 | {posts.map(({ node }) => {
  32 |   const { frontmatter, timeToRead, fields: { slug }, excerpt } = node;
  33 |   const avatar = frontmatter.author.avatar.children[0] as ImageSharp;
> 34 |   const cover = frontmatter.image.children[0] as ImageSharp;
  35 | 
  36 |   const extra = (
  37 |     <Comment.Group>
View compiled
./src/pages/blog.tsx.exports.default.props
src/pages/blog.tsx:29
  26 | const pageCount = Math.ceil(props.data.posts.totalCount / 10);
  27 | 
  28 | // TODO export posts in a proper component
> 29 | const Posts = (
  30 |   <Container>
  31 |     {posts.map(({ node }) => {
  32 |       const { frontmatter, timeToRead, fields: { slug }, excerpt } = node;
  
  ```

**Comment by mghazwi** [comment]
i tried it again and got different error:
TypeError: Cannot read property 'tags' of undefined
./src/pages/blog.tsx.exports.default.props
src/pages/blog.tsx:23
  20 | }
  21 | 
  22 | export default (props: BlogProps) => {
> 23 |   const tags = props.data.tags.group;
  24 |   const posts = props.data.posts.edges;
  25 |   const { pathname } = props.location;
  26 |   const pageCount = Math.ceil(props.data.posts.totalCount / 10);

**Comment by dvulanov** [comment]
This code requires an image and tag for blog posts.  If they are not specified in the frontmatter then errors are thrown.  You should specify both and make sure the image in located local to the post.

**Comment by i001962** [comment]
I too am getting this error. It seams that changing the Author ID causes the error. I wondered if it has something to do with blogs.tsx line 28 
  // TODO export posts in a proper component

The starter content worked as expected and I could see the blog posts. Then I created a new folder under blogs to hold the new post (index.md and the image). When I went to change author ID from 'fabien BENARD' to a new name in both the author.json and index.md the error occurs. Any thoughts? My gatsby knowledge is all of 4 tutorials. Appreciate any pointers you may have on how to fix this.

**Comment by fabien0102** [comment]
@i001962 @mghazwi Just to be sure, this is resolve for you? 
If yes, you can maybe add some useful tips in the README.md (I accept PR 😃 ) It's not always easy to explained how everything works, so some externals feedbacks is always a good point for me 👍

**Comment by fabien0102** [comment]
@sielay Not a bad idea! I will add this also in this starter ;)

**Comment by fabien0102** [comment]
@sielay BTW, you can totally remove your check, `cover` is unused in your project 😄

**Comment by sielay** [comment]
Sometimes I use sometimes no :P You know what would be awesome? 

I saw recently repo that uses Proxies that returns itself helping to avoid issues with null/undefined in the chain. Can't dig it out, but would be awesome to use such approach without checks each time.

**Comment by sielay** [comment]
I meant those https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy. I will try to dig out the specific project. It works like magic method in PHP. Basically, you have an object which can carry null/undefined, but if you ask for children that don't exist it safely gives you undefined instead of crashing.

**Comment by fabien0102** [comment]
Interesting! But definitively `lodash.get` ^^ Proxy can be nice, but a little bit overkill for this usecase on my own opinion.

```js
var object = { 'a': [{ 'b': { 'c': 3 } }] };
 
_.get(object, 'a[0].b.c');
// => 3
 
_.get(object, ['a', '0', 'b', 'c']);
// => 3
 
_.get(object, 'a.b.c', 'default');
// => 'default'
```

https://lodash.com/docs/4.17.5#get

**Comment by i001962** [comment]
@fabien0102 just submitted PR #61  for the README.md. It will be my first contribution (ever) if you find it acceptable.  Noob learning.

**Comment by fabien0102** [comment]
@i001962 Welcome to beautiful world of the open source 😁
