### ISSUE TITLE
Fails to build/develop (on Windows?)

### ISSUE THREAD

**Issue by arlobelshee** [fabien0102/gatsby-starter#56]
On a clean starter, `gatsby develop` results in unhandled exception cannot find module 'sharp'. During `gatsby new`, `npm` warned me "skipping optional dependency: sharp".

Please make sharp either truly optional or truly required (and installed). As is, the starter builds a site that cannot be used.

I assume this must be OS-specific, since it's a total-fail bug.

**Comment by fabien0102** [comment]
^^ Classic! Don't worry, I'm also on windows 😉 https://www.gatsbyjs.org/docs/gatsby-on-windows/#gatsby-on-windows I write an article about this kind of issue ^^

> `npm install windows-build-tools -g` on an admin PowerShell console.

and reinstall everything from scratch

**Comment by arlobelshee** [comment]
Thank you! Fixed.
