### ISSUE TITLE
yarn build fail on clean install

### ISSUE THREAD

**Issue by mulyoved** [fabien0102/gatsby-starter#58]
```
gatsby new my-website https://github.com/fabien0102/gatsby-starter
yarn add --dev babel-loader@7.1.1
yarn build
```

Faild with TS errors,  
![4-18-2018 11-07-29 am](https://user-images.githubusercontent.com/2309907/38919256-c1c7af24-42f8-11e8-8b6f-f4c1ce76e68e.png)

Set `noImplicitAny = false` also does not help as fail due to other errors

```
tsc --version
2.5.3
```

**Comment by fabien0102** [comment]
And with npm instead of yarn? (we have some weird packages conflicts between gatsby and storybook with yarn…)

**Comment by mulyoved** [comment]
```
rm -rf node_modules/
npm install
npm build
```

also fail

**Comment by fabien0102** [comment]
@mulyoved Sorry for this, I need to investigate a little bit more to understand what happen and find a solution. You can also try to just clone this repo (without the gatsby-cli) and `rm -rf .git` if it's working.
Let me know if this solution is working for you :)

**Comment by mulyoved** [comment]
git clone and then yarn or npm install + build also didn't work, same failures

**Comment by fabien0102** [comment]
Oki… for the record, which os and node version do you use?

**Comment by mulyoved** [comment]
Windows
node 8.10.0

**Comment by sielay** [comment]
@mulyoved  Had the same issues. For starters remove implicitly from `tsconfig.json`. Code from starter should work. Problems start when you try to add other dependencies and typescript, webpack and few other packages start to rage with an incompatible version. Over here you can find some trails and errors trying to find the issue https://github.com/fabien0102/gatsby-starter/pull/55

**Comment by ashfurrow** [comment]
I just experienced a similar error on a fresh build, with both Yarn and npm. 

<details>
<summary>Here's the error log</summary>

```
npm start

> gatsby-starter@1.0.0 start /Users/ash/bin/blog2/blog
> gatsby develop

success delete html and css files from previous builds — 0.013 s
success open and validate gatsby-config — 0.005 s
success copy gatsby files — 0.014 s
success onPreBootstrap — 0.419 s
success source and transform nodes — 0.183 s
success building schema — 0.260 s
success createLayouts — 0.009 s
success createPages — 0.032 s
success createPagesStatefully — 0.020 s
success onPreExtractQueries — 0.001 s
success update schema — 0.166 s
success extract queries from components — 0.358 s
success run graphql queries — 0.298 s
success write out page data — 0.003 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 3.569 s

error There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND


  Error: Module build failed: TypeError: fileSystem.statSync is not a function

  - exists.js:7 module.exports
    [blog]/[babel-loader]/lib/utils/exists.js:7:25

  - resolve-rc.js:13 find
    [blog]/[babel-loader]/lib/resolve-rc.js:13:9

  - index.js:111 Object.module.exports
    [blog]/[babel-loader]/lib/index.js:111:132


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter@1.0.0 start: `gatsby develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ash/.npm/_logs/2018-05-05T16_48_51_683Z-debug.log
```

</details>

I updated to use Node to 9.10.1 as suggested by @i001962 above and it now works. Thanks for the workaround! Let me know if I can help provide any other details.

**Comment by fabien0102** [comment]
Should be fixed, please tell if it's still broken ;) (I'm just cleaning a bit our issues ^^)
