### ISSUE TITLE
Storybook fails on clean install

### ISSUE THREAD

**Issue by ccjjmartin** [fabien0102/gatsby-starter#66]
## Steps to reproduce:

1. - `gatsby new project https://github.com/fabien0102/gatsby-starter/`
2. - `cd project`
3. - Make sure you don't have anything running on port 9001
4. - `yarn run storybook`

## Get this error:

`ERROR in /Users/developer/gatsby/project/node_modules/@types/react-router/index.d.ts
(110,50): error TS2304: Cannot find name 'Exclude'.`

## Found the fix in this open PR:

https://github.com/fabien0102/gatsby-starter/pull/64/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R66

## Fix:
Upgrade typescript package (in package.json) to `2.8.3` fixed it for me.

**Comment by sielay** [comment]
Thanks for this one! It's missing bit to this https://github.com/fabien0102/gatsby-starter/pull/64

**Comment by mattdell** [comment]
@ccjjmartin I've been trying to resolve this for ages _before_ updating my TypeScript version. Cannot believe it was as simple to resolve as just updating TypeScript.

**THANK YOU**
