### ISSUE TITLE
Is `src/templates/blog-page.tsx` a redundant file?

### ISSUE THREAD

**Issue by rojobuffalo** [fabien0102/gatsby-starter#67]
I'm new to gatsby and there's a lot going on that I'm trying to understand. When I look at the file `src/templates/blog-page.tsx` and grep the project to see where that file gets used, it doesn't make any sense to me. Is that file getting used anywhere? I only see it getting used in `test/__snapshots__/gatsby-node.test.js.snap`.

**Comment by fabien0102** [comment]
Just [here](https://github.com/fabien0102/gatsby-starter/blob/master/gatsby-node.js#L57
), gatsby read the content from `/data` (the graphql query) and create pages from the query result (that look like this -> https://github.com/fabien0102/gatsby-starter/blob/master/test/gatsby-node.test.js#L76) using the template into `createPage` (method provide by the frameworks to inject some page)

But I must admit that this part can be a little bit magic 😄 (it's also the interesting part of gatsby)

**Comment by rojobuffalo** [comment]
@fabien0102 thank you for clarifying that!
