### ISSUE TITLE
Cannot read tags group.

### ISSUE THREAD

**Issue by shockw4ver** [fabien0102/gatsby-starter#71]
I deleted three sample posts, and generator new one, and when I get into the ``/blog/`` , it errored me ``Cannot read property 'group' of null``.
Entire Error:
```
./src/pages/blog.tsx.exports.default
src/pages/blog.tsx:24
  21 | }
  22 | 
  23 | export default (props: BlogProps) => {
> 24 |   const tags = props.data.tags.group;
  25 |   const posts = props.data.posts.edges;
  26 |   const { pathname } = props.location;
  27 |   const pageCount = Math.ceil(props.data.posts.totalCount / 10);
```

**Comment by shockw4ver** [comment]
Now I found the way to resolve it, but how to extends the graphql-types is the new question...😅
I modified the ``graphql-types.d.ts`` file, but still cannot query the new field.

**Comment by shockw4ver** [comment]
Thanks~  I did so to resolve it and made same changes at others place.
Looking forward to enjoy the starter with new gatsby！🤓

**Comment by i001962** [comment]
Closing this issue. Works as designed. @shockw4ver if you disagree please comment.
