### ISSUE TITLE
Move `next` to `master`, move current `master` to `v1`

### ISSUE THREAD

**Issue by jlengstorf** [fabien0102/gatsby-starter#80]
Hey, there! Now that Gatsby V2 has been out for a while, would it make sense to make the `next` branch the default branch? Most new instances will be against Gatsby V2, so making that the default would be ideal.

Thanks!

**Comment by fabien0102** [comment]
Very good idea! let’s do this! 🎉

**Comment by fabien0102** [comment]
Closed by #81
