### ISSUE TITLE
Not work with node v11.11.0 && npm v6.7.0 && gatsby v2.4.10

### ISSUE THREAD

**Issue by nikbelikov** [fabien0102/gatsby-starter#87]
`
gatsby new my-website https://github.com/fabien0102/gatsby-starter
error Directory my-website is already an npm project
MacBook-Pro-Nikolaj:jest nikbelikov$ gatsby new my-website https://github.com/fabien0102/gatsby-starter
info Creating new site from git: https://github.com/fabien0102/gatsby-starter.git
Cloning into 'my-website'...
remote: Enumerating objects: 1397, done.
remote: Total 1397 (delta 0), reused 0 (delta 0), pack-reused 1397
Receiving objects: 100% (1397/1397), 15.23 MiB | 5.88 MiB/s, done.
Resolving deltas: 100% (865/865), done.
success Created starter directory layout
info Installing packages...
npm WARN npm npm does not support Node.js v11.11.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! code ETARGET
npm ERR! notarget No matching version found for gatsby-remark-autolink-headers@next
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'gatsby-starter'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nikbelikov/.npm/_logs/2019-03-10T16_13_59_111Z-debug.log
error Command failed: npm install

  Error: Command failed: npm install

  - index.js:236 Promise.all.then.arr
    [lib]/[gatsby-cli]/[execa]/index.js:236:11

  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18

  - async.js:138 _drainQueueStep
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12

  - async.js:131 _drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:131:9

  - async.js:147 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:147:5

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14
`

**Comment by AbhimanyuAryan** [comment]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for gatsby-link@next
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'gatsby-starter'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abhimanyuaryan/.npm/_logs/2019-03-10T22_20_41_082Z-debug.log

**Comment by AbhimanyuAryan** [comment]
@fabien0102 can you let us know why this is happening? I'm using an older version of this blog with yarn & suddenly it stopped deploying to production(gitlab)

Can you please help us with priority? Or I'll have to move my blog to some stable alternative

**Comment by AbhimanyuAryan** [comment]
This is fixed

**Comment by bensontrent** [comment]
Fixed by #89
